# Default config for the Red Hat CFME-QE team.

# Define auth settings. Username/password only needed if doing basic authentication
auth:
  kerberos: true
  basic_auth: false
  username: null
  # NOTE: password is stored in plain text! Use kerberos if you can. Otherwise,
  # leave the password as 'null' if you want to type it in every time you start
  # for a more secure option
  password: null

# Name or ID of agile board
board: "CloudForms QE Sprints"

# Name, key, or ID of project
project: "Red Hat CloudForms QE"

# JIRA server base URL
url: https://projects.engineering.redhat.com

# Path to certificate authority trust file
ca_cert_path: "/etc/ssl/certs/ca-bundle.crt"

# Whether or not to validate SSL certs when connecting to JIRA
verify_ssl: True

# Whether or not to check that components have valid labels
label_check: True

# Whether to always check (and sync if needed) your config's components_labels_map with those in default config
sync_to_defaults: true

# Map of valid labels for each components
components_labels_map:
  infrastructure:
    - "jenkins"
    - "polarion"
    - "documentation"
    - "tooling"
    - "provider-gce"
    - "provider-rhevm"
    - "provider-vmware"
    - "provider-osp"
    - "provider-rhos"
    - "provider-azure"
    - "provider-ec2"
    - "provider-scvmm"
    - "provider-cm"
    - "infra-gce"
    - "infra-rhevm"
    - "infra-vmware"
    - "infra-rhos"
    - "infra-ec2"
    - "other"
  testing:
    - "cloudforms"
    - "satforms"
    - "vmass"
    - "cfme-5.9"
    - "cfme-5.8"
    - "upstream"
    - "miq-demo"
    - "on-qa"
    - "pteam"
    - "templates"
    - "other"
  management:
    - "cloudforms"
    - "satforms"
    - "vmass"
    - "meeting"
    - "bug-work"
    - "jira"
    - "other"
  automation:
    - "cloudforms"
    - "satforms"
    - "vmass"
    - "framework"
    - "auto-test-fix"
    - "new-test"
    - "pr-review"
    - "results-review"
    - "other"
  documentation:
    - "polarion"
    - "bug-work"
    - "automation"
    - "mojo"
    - "other"
  training:
    - "personal"
    - "other"
